#!/usr/bin/env bash

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
for i in {0..7}; do
  printf -v fbright$i %b "\e[9${i}m"
done

bld=$'\e[1m'
rst=$'\e[0m'

cat <<EOF
 
 $f1███$bld▄$rst  $f2███$bld▄$rst  $f3███$bld▄$rst  $f4███$bld▄$rst  $f5███$bld▄$rst  $f6███$bld▄$rst  $f7███$bld▄$rst
 $f1███$bld█$rst  $f2███$bld█$rst  $f3███$bld█$rst  $f4███$bld█$rst  $f5███$bld█$rst  $f6███$bld█$rst  $f7███$bld█$rst
 $f1███$bld█$rst  $f2███$bld█$rst  $f3███$bld█$rst  $f4███$bld█$rst  $f5███$bld█$rst  $f6███$bld█$rst  $f7███$bld█$rst
 $d$f1 ▀▀▀   $f2▀▀▀   $f3▀▀▀   $f4▀▀▀   $f5▀▀▀   $f6▀▀▀   $f7▀▀▀
EOF
