#!/bin/sh

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

esc=""

redf="${esc}[31m"
greenf="${esc}[32m"
yellowf="${esc}[33m"
bluef="${esc}[34m"
purplef="${esc}[35m"
cyanf="${esc}[36m"

redfbright="${esc}[91m"
greenfbright="${esc}[92m"
yellowfbright="${esc}[93m"
bluefbright="${esc}[94m"
purplefbright="${esc}[95m"
cyanfbright="${esc}[96m"

boldon="${esc}[1m"
invon="${esc}[7m"

reset="${esc}[0m"

cat <<EOF

${invon}
${redf}   ▄█     █▄    ${greenf}   ▄▄     ▄▄    ${yellowf}   ▄▄     ▄▄    ${bluef}   ▄▄     ▄▄    ${purplef}   ▄▄     ▄▄    ${cyanf}   ▄█     █▄   
${redf} ▄█▀  ▄▄▄  ▀█▄  ${greenf} ▄█▀  ▄▄▄  ▀█▄  ${yellowf} ▄█▀  ▄▄▄  ▀█▄  ${bluef} ▄█▀  ▄▄▄  ▀█▄  ${purplef} ▄█▀  ▄▄▄  ▀█▄  ${cyanf} ▄█▀  ▄▄▄  ▀█▄ 
${redf} ██▄▄██▀██▄▄██  ${greenf} ██▄▄██▀██▄▄██  ${yellowf} ██▄▄██▀██▄▄██  ${bluef} ██▄▄██▀██▄▄██  ${purplef} ██▄▄██▀██▄▄██  ${cyanf} ██▄▄██▀██▄▄██ 
${redf} ██▀▀█████▀▀██  ${greenf} ██▀▀█████▀▀██  ${yellowf} ██▀▀█████▀▀██  ${bluef} ██▀▀█████▀▀██  ${purplef} ██▀▀█████▀▀██  ${cyanf} ██▀▀█████▀▀██ 
${redf} ▀█▄  ▀▀▀  ▄█▀  ${greenf} ▀█▄  ▀▀▀  ▄█▀  ${yellowf} ▀█▄  ▀▀▀  ▄█▀  ${bluef} ▀█▄  ▀▀▀  ▄█▀  ${purplef} ▀█▄  ▀▀▀  ▄█▀  ${cyanf} ▀█▄  ▀▀▀  ▄█▀ 
${redf}   ▀█     █▀    ${greenf}   ▀▀     ▀▀    ${yellowf}   ▀▀     ▀▀    ${bluef}   ▀▀     ▀▀    ${purplef}   ▀▀     ▀▀    ${cyanf}   ▀█     █▀   
${boldon}${invon}
${redfbright}   ▄█     █▄    ${greenfbright}   ▄▄     ▄▄    ${yellowfbright}   ▄▄     ▄▄    ${bluefbright}   ▄▄     ▄▄    ${purplefbright}   ▄▄     ▄▄    ${cyanfbright}   ▄█     █▄   
${redfbright} ▄█▀  ▄▄▄  ▀█▄  ${greenfbright} ▄█▀  ▄▄▄  ▀█▄  ${yellowfbright} ▄█▀  ▄▄▄  ▀█▄  ${bluefbright} ▄█▀  ▄▄▄  ▀█▄  ${purplefbright} ▄█▀  ▄▄▄  ▀█▄  ${cyanfbright} ▄█▀  ▄▄▄  ▀█▄ 
${redfbright} ██▄▄██▀██▄▄██  ${greenfbright} ██▄▄██▀██▄▄██  ${yellowfbright} ██▄▄██▀██▄▄██  ${bluefbright} ██▄▄██▀██▄▄██  ${purplefbright} ██▄▄██▀██▄▄██  ${cyanfbright} ██▄▄██▀██▄▄██ 
${redfbright} ██▀▀█████▀▀██  ${greenfbright} ██▀▀█████▀▀██  ${yellowfbright} ██▀▀█████▀▀██  ${bluefbright} ██▀▀█████▀▀██  ${purplefbright} ██▀▀█████▀▀██  ${cyanfbright} ██▀▀█████▀▀██ 
${redfbright} ▀█▄  ▀▀▀  ▄█▀  ${greenfbright} ▀█▄  ▀▀▀  ▄█▀  ${yellowfbright} ▀█▄  ▀▀▀  ▄█▀  ${bluefbright} ▀█▄  ▀▀▀  ▄█▀  ${purplefbright} ▀█▄  ▀▀▀  ▄█▀  ${cyanfbright} ▀█▄  ▀▀▀  ▄█▀ 
${redfbright}   ▀█     █▀    ${greenfbright}   ▀▀     ▀▀    ${yellowfbright}   ▀▀     ▀▀    ${bluefbright}   ▀▀     ▀▀    ${purplefbright}   ▀▀     ▀▀    ${cyanfbright}   ▀█     █▀   
${reset}

EOF
