#!/bin/sh

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

esc=""

redf="${esc}[31m"
greenf="${esc}[32m"
bluef="${esc}[34m"
purplef="${esc}[35m"
cyanf="${esc}[36m"

reset="${esc}[0m"

cat <<EOF

${greenf}█         █   ${redf}█         █   ${bluef}█         █   ${purplef}█         █   ${cyanf}█         █
${greenf}█   ▄▄▄   █   ${redf}█   ▄▄▄   █   ${bluef}█   ▄▄▄   █   ${purplef}█   ▄▄▄   █   ${cyanf}█   ▄▄▄   █
${greenf}█▄▄██▀██▄▄█   ${redf}█▄▄██▀██▄▄█   ${bluef}█▄▄██▀██▄▄█   ${purplef}█▄▄██▀██▄▄█   ${cyanf}█▄▄██▀██▄▄█
${greenf}█▀▀█████▀▀█   ${redf}█▀▀█████▀▀█   ${bluef}█▀▀█████▀▀█   ${purplef}█▀▀█████▀▀█   ${cyanf}█▀▀█████▀▀█
${greenf}█   ▀▀▀   █   ${redf}█   ▀▀▀   █   ${bluef}█   ▀▀▀   █   ${purplef}█   ▀▀▀   █   ${cyanf}█   ▀▀▀   █
${greenf}█         █   ${redf}█         █   ${bluef}█         █   ${purplef}█         █   ${cyanf}█         █
${reset}

EOF
