#!/bin/sh

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

esc=""

blackf="${esc}[30m"

yellowb="${esc}[43m"
cyanb="${esc}[46m"
whiteb="${esc}[47m"

reset="${esc}[0m"

tuxbg=${cyanb}  # color behind tux
tuxfg=${blackf} # tux line color

cat <<EOF
${tuxfg}${tuxbg}
                                                     
                      ▄█████▄                        
                     █████████                       
                    ${whiteb}████████▀██${tuxbg}                      
                   ${whiteb}██████████▄██${tuxbg}                     
                   ${whiteb}██▀▀███▀▀████${tuxbg}                     
                   ${whiteb}████ █ ██ ███${tuxbg}                     
                   ${yellowb}█         ████${tuxbg}                    
                   ${yellowb}█       ▄ ████${tuxbg}                    
                   ${yellowb}███▀▀▀▀▀▄${whiteb}▀████${tuxbg}                    
                   ${whiteb}██▀▀▀▀▀▀   ███${tuxbg}▄                   
                 ▄█${whiteb}▀          █████${tuxbg}                  
                ${whiteb}███           ██████${tuxbg}                 
               ${whiteb}███             ██████${tuxbg}                
              ${whiteb}█▀██              ██████${tuxbg}               
              ${whiteb}█ █               █ ████${tuxbg}               
              ${whiteb}█ █               ██ ███${tuxbg}               
             ${whiteb}██ ▀               █▀ ████${tuxbg}              
             ${whiteb}███                   ████${tuxbg}              
            ${whiteb}█████               ███ ███${tuxbg}              
            ${yellowb}█▀▀███${whiteb}             █████████${tuxbg}             
           ▄${yellowb}█   ███${whiteb}           █${yellowb}▀ ████  ▀█${tuxbg}            
        █${yellowb}         ████${whiteb}     █  █${yellowb}         ██${tuxbg}           
         █${yellowb}         ██${whiteb}       █ █${yellowb}          ▀█${tuxbg}          
        █${yellowb}           █${whiteb}      █  █${yellowb}          █${tuxbg}           
        █${yellowb}           ███████████${yellowb}        ▄${tuxbg}▀            
         █${yellowb}▄         █${tuxbg} ▀▀▀▀▀▀▀ █${yellowb}      ▄${tuxbg}▀              
           ▀▀▀▀▀${yellowb}▄▄▄█${tuxbg}▀         ▀${yellowb}▄    █${tuxbg}                
                                ▀▀▀▀${tuxbg}                 
${reset}
EOF
